[package]
name = "jose-jwe"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
description = """
Pure Rust implementation of the JSON Web Encryption (JWE) component of the
Javascript Object Signing and Encryption (JOSE) specification as described in
RFC7516
"""
documentation = "https://docs.rs/jose-jwe"
homepage = "https://github.com/RustCrypto/JOSE/tree/master/jose-jwe"
categories = ["cryptography", "data-structures", "encoding", "parser-implementations"]
keywords = ["json", "jose", "jwe", "encryption"]
readme = "README.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
crypto = ["aes-cbc-hmac", "aes-gcm"]
aes-cbc-hmac = ["dep:aes"]
aes-gcm = ["dep:aes-gcm", "cipher", "getrandom", "rand_core", "zeroize/alloc"]

[dependencies]
jose-b64 = { workspace = true }
jose-jwa = { workspace = true }
jose-jwk = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
zeroize = { workspace = true }

# Optional crypto dependencies
aes = { workspace = true, default-features = false, optional = true }
aes-gcm = { workspace = true, default-features = false, optional = true, features = ["alloc"] }
cipher = { workspace = true, optional = true }
getrandom = { workspace = true, optional = true }
rand_core = { workspace = true, default-features = false, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
