[package]
name = "jose-jwe"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
description = """
Pure Rust implementation of the JSON Web Encryption (JWE) component of the
Javascript Object Signing and Encryption (JOSE) specification as described in
RFC7516
"""
documentation = "https://docs.rs/jose-jwe"
homepage = "https://github.com/RustCrypto/JOSE/tree/master/jose-jwe"
repository.workspace = true
categories = ["cryptography", "data-structures", "encoding", "parser-implementations"]
keywords = ["json", "jose", "jwe", "encryption"]
readme = "README.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
jose-b64 = { workspace = true }
jose-jwa = { workspace = true }
jose-jwk = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

zeroize = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
