[package]
name = "jose-jwa"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
description = """
Pure Rust implementation of the JSON Web Algorithm (JWA) component of the
Javascript Object Signing and Encryption (JOSE) specification as described in
RFC7518
"""
documentation = "https://docs.rs/jose-jwa"
homepage = "https://github.com/RustCrypto/JOSE/tree/master/jose-jwa"
repository.workspace = true
categories = ["cryptography", "data-structures", "encoding", "parser-implementations"]
keywords = ["json", "jose", "jwa"]
readme = "README.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
