[package]
name = "jose-jwa"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
description = """
Pure Rust implementation of the JSON Web Algorithm (JWA) component of the
Javascript Object Signing and Encryption (JOSE) specification as described in
RFC7518
"""
documentation = "https://docs.rs/jose-jwa"
homepage = "https://github.com/RustCrypto/JOSE/tree/master/jose-jwa"
repository.workspace = true
categories = ["cryptography", "data-structures", "encoding", "parser-implementations"]
keywords = ["json", "jose", "jwa"]
readme = "README.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
crypto = ["aes-gcm", "aes-kw", "hmac", "p256", "p384", "p521", "k256", "rsa", "sha1", "sha2"]
# Include legacy/vulnerable algorithms (not recommended for production)
legacy = ["legacy-rsa1_5"]
legacy-rsa1_5 = []

[dependencies]
serde = { workspace = true }

# optional dependencies
aes-gcm = { workspace = true, default-features = false, optional = true }
aes-kw = { workspace = true, default-features = false, optional = true }
hmac = { workspace = true, default-features = false, optional = true }
k256 = { workspace = true, default-features = false, optional = true, features = ["arithmetic"] }
p256 = { workspace = true, default-features = false, optional = true, features = ["arithmetic"] }
p384 = { workspace = true, default-features = false, optional = true, features = ["arithmetic"] }
p521 = { workspace = true, default-features = false, optional = true, features = ["arithmetic"] }
rsa = { workspace = true, default-features = false, optional = true }
sha1 = { workspace = true, default-features = false, optional = true }
sha2 = { workspace = true, default-features = false, optional = true }

[dev-dependencies]
getrandom = { workspace = true }
serde_json = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
