[package]
name = "jose-jwa"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
description = """
Pure Rust implementation of the JSON Web Algorithm (JWA) component of the
Javascript Object Signing and Encryption (JOSE) specification as described in
RFC7518
"""
documentation = "https://docs.rs/jose-jwa"
homepage = "https://github.com/RustCrypto/JOSE/tree/master/jose-jwa"
repository.workspace = true
categories = ["cryptography", "data-structures", "encoding", "parser-implementations"]
keywords = ["json", "jose", "jwa"]
readme = "README.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []

aes-cbc-hmac = ["dep:aes", "cbc", "hmac", "dep:jose-b64", "rand_core", "sha2", "subtle"]
aes-gcm = ["dep:aes-gcm", "digest", "dep:jose-b64", "rand_core"]
aes-kw = ["dep:aes", "dep:aes-kw", "digest"]
ecdh = ["dep:aes-kw", "dep:elliptic-curve", "dep:jose-b64","dep:p256", "dep:p384", "dep:p521", "rand_core", "sha2"]
hmac = ["dep:aes-gcm", "dep:hmac", "dep:jose-b64", "sha2", "subtle"]
k256 = ["dep:k256", "digest", "ecdsa", "dep:jose-b64", "sha2"]
p256 = ["dep:p256", "digest", "ecdsa", "dep:jose-b64", "sha2"]
p384 = ["dep:p384", "digest", "ecdsa", "dep:jose-b64", "sha2"]
p521 = ["dep:p521", "digest", "ecdsa", "dep:jose-b64", "sha2"]
pbes2 = ["aes-kw", "dep:hmac", "dep:pbkdf2", "rand_core", "sha2"]
rsa = ["dep:rsa", "dep:jose-b64", "rand_core", "sha1", "sha2"]

# Include legacy/vulnerable algorithms (not recommended for production)
legacy = ["legacy-rsa1_5"]
legacy-rsa1_5 = []

[dependencies]
serde = { workspace = true }
zeroize = { workspace = true, default-features = false, features = ["alloc", "derive"] }

# optional dependencies
aes = { workspace = true, default-features = false, optional = true }
aes-gcm = { workspace = true, default-features = false, optional = true, features = ["alloc"] }
aes-kw = { workspace = true, default-features = false, optional = true }
cbc = { workspace = true, default-features = false, optional = true, features = ["alloc", "block-padding"] }
digest = { workspace = true, default-features = false, optional = true }
ecdsa = { workspace = true, default-features = false, optional = true, features = ["digest"] }
elliptic-curve = { workspace = true, default-features = false, optional = true, features = ["ecdh"] }
hmac = { workspace = true, default-features = false, optional = true }
jose-b64 = { workspace = true, optional = true }
k256 = { workspace = true, default-features = false, optional = true, features = ["arithmetic"] }
p256 = { workspace = true, default-features = false, optional = true, features = ["arithmetic"] }
p384 = { workspace = true, default-features = false, optional = true, features = ["arithmetic"] }
p521 = { workspace = true, default-features = false, optional = true, features = ["arithmetic"] }
rand_core = { workspace = true, default-features = false, optional = true }
rsa = { workspace = true, default-features = false, optional = true, features = ["getrandom", "hazmat"] }
sha1 = { workspace = true, default-features = false, optional = true }
sha2 = { workspace = true, default-features = false, optional = true }
pbkdf2 = { workspace = true, default-features = false, optional = true, features = ["hmac"] }
subtle = { workspace = true, default-features = false, optional = true }

[dev-dependencies]
getrandom = { workspace = true, features = ["sys_rng"] }
serde_json = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
