[package]
name = "jose-b64"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
description = "Base64 utilities for use in JOSE crates"
documentation = "https://docs.rs/jose-b64"
homepage = "https://github.com/RustCrypto/JOSE/tree/master/jose-b64"
repository.workspace = true
categories = ["cryptography", "data-structures", "encoding", "parser-implementations"]
keywords = ["json", "jose"]
readme = "README.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
secret = ["serde", "dep:zeroize", "dep:subtle"]
json = ["serde", "dep:serde_json"]
serde = ["dep:serde"]

[dependencies]
base64ct = { workspace = true }

# optional dependencies
zeroize = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
subtle = { workspace = true, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
