[package]
name = "jose-jwk"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
description = """
Pure Rust implementation of the JSON Web Key (JWK) component of the
Javascript Object Signing and Encryption (JOSE) specification as described in
RFC7517
"""
documentation = "https://docs.rs/jose-jwk"
homepage = "https://github.com/RustCrypto/JOSE/tree/master/jose-jwk"
repository.workspace = true
categories = ["cryptography", "data-structures", "encoding", "parser-implementations"]
keywords = ["json", "jose", "jwk"]
readme = "README.md"

version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["crypto"]
crypto = ["p256", "p384", "p521", "k256", "rsa"]
legacy = ["dep:base64ct", "dep:elliptic-curve", "dep:serde_json", "dep:serdect", "dep:subtle"]
thumbprint = ["dep:sha2"]

[dependencies]
jose-b64 = { workspace = true }
jose-jwa = { workspace = true }
serde = { workspace = true }
zeroize = { workspace = true }

# optional dependencies
p256 = { workspace = true, optional = true }
p384 = { workspace = true, optional = true }
p521 = { workspace = true, optional = true }
k256 = { workspace = true, optional = true }
rsa = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
url = { workspace = true, optional = true }

# legacy dependencies
base64ct = { workspace = true, optional = true }
elliptic-curve = { workspace = true, optional = true }
serdect = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
subtle = { workspace = true, optional = true }

[dev-dependencies]
elliptic-curve = { workspace = true, features = ["dev"] }
serde_json = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
